# Generated by Django 4.1 on 2022-08-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emailId', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
